version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: noahhhhhhh/my-reading-habits:latest
    container_name: my-reading-habits
    command: ["python", "main.py"]
