name: Convert & Deploy

on:
  push:
    branches:
      - main
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Convert-Deploy"
  Convert-Deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the repository
        uses: actions/checkout@v4
      
      # Updates Node.js version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        
      # Uses an updated layer caching without deprecation warnings
      - name: Docker Layer Caching
        uses: jpribyl/action-docker-layer-caching@v0.1.1
        continue-on-error: true
        
      - name: free disk space
        run: |
        sudo rm -f /swapfile
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h
      
      # Builds docker image
      - name: Build docker images
        run: docker build -t booksread . -f Dockerfile

      # Converts .ipynb to html
      - name: Convert notebook
        run: docker run -v $PWD/docs:/app/docs booksread make convert

      - name: List files in the docs folder
        run: |
          ls docs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: docs # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
      - run: echo "This job's status is ${{ job.status }}."
